// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Cancel
       * @returns {Promise<void>} 
       */
      "Cancel": () => {
        return window.go.main.App.Cancel();
      },
      /**
       * Copy
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<Error>}  - Go Type: error
       */
      "Copy": (arg1) => {
        return window.go.main.App.Copy(arg1);
      },
      /**
       * GetBannerLog
       * @param {URL} arg1 - Go Type: *url.URL
       * @returns {Promise<void>} 
       */
      "GetBannerLog": (arg1) => {
        return window.go.main.App.GetBannerLog(arg1);
      },
      /**
       * GetJson
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<WishResponse|Error>}  - Go Type: *main.WishResponse
       */
      "GetJson": (arg1) => {
        return window.go.main.App.GetJson(arg1);
      },
      /**
       * GetLog
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "GetLog": (arg1) => {
        return window.go.main.App.GetLog(arg1);
      },
      /**
       * GetWishes
       * @param {URL} arg1 - Go Type: *url.URL
       * @param {number} arg2 - Go Type: int
       * @returns {Promise<Array.<string>|Error>}  - Go Type: []string
       */
      "GetWishes": (arg1, arg2) => {
        return window.go.main.App.GetWishes(arg1, arg2);
      },
      /**
       * ResizeWindow
       * @param {number} arg1 - Go Type: int
       * @param {number} arg2 - Go Type: int
       * @returns {Promise<void>} 
       */
      "ResizeWindow": (arg1, arg2) => {
        return window.go.main.App.ResizeWindow(arg1, arg2);
      },
      /**
       * SaveToDownload
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<Error>}  - Go Type: error
       */
      "SaveToDownload": (arg1) => {
        return window.go.main.App.SaveToDownload(arg1);
      },
      /**
       * Start
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "Start": (arg1) => {
        return window.go.main.App.Start(arg1);
      },
    },
  },

};
export default go;
